import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1700, height: 1100 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:5173/');
await p.waitForFunction(() => window.__craft);
const id = await p.evaluate(() => { const c = window.__craft; return [...c.DB.items.values()].find(i => c.DB.text(i.label) === 'Lunar Amulet' && i.domain === 1).id; });
await p.goto(`http://localhost:5173/?group=5&class=34&item=${id}`);
await p.waitForSelector('#itemBox');
await p.evaluate(async () => {
  const c = window.__craft, E = await import('/js/engine.js');
  c.S.item.ilvl = 60;
  for (let k = 0; k < 4; k++) E.applyMethod(c.S.item, { handler: 'poe2_catalyst_flesh', properties: [], constraints: [] });
  c.S.item.rarity = 'rare';
  for (let k = 0; k < 4; k++) E.applyMethod(c.S.item, { handler: 'poe2_exalted', properties: [], constraints: [] });
  c.renderCraft();
});
console.log('tabs:', await p.locator('.tabs .chip').allInnerTexts());
await p.locator('[data-tab=Catalysts]').click();
const names = await p.locator('#currencies .cur').allInnerTexts();
console.log('catalyst buttons:', names.length, names.slice(0, 3), 'disabled:', await p.locator('#currencies .cur[disabled]').count());
await p.locator('#currencies .cur', { hasText: 'Flesh' }).click();
await p.locator('#itemBox').click();
console.log('after click:', (await p.locator('#itemBox').innerText()).split(String.fromCharCode(10)).find(l => l.startsWith('Quality (')));
console.log('omens page text has Catalysing:', (await p.locator('body').innerText()).includes('Catalysing'));
await p.screenshot({ path: 'recon/catalyst-page.png' });
await p.locator('#tooltip').screenshot({ path: 'recon/catalyst-item.png' });
await p.screenshot({ path: 'recon/catalyst-page.png' });
console.log(errs.length ? errs.join('\n') : 'no errors');
await b.close();
