import { chromium } from 'playwright';
import fs from 'fs';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 1100 } });
await p.route(/(nitropay|doubleclick|googletag|google-analytics|amazon-adsystem|id5|criteo|adsrvr|privacymanager|scalibur|hadronid|rlcdn|fastclick|ad\.gt)/, r => r.abort());
await p.goto('https://beta.craftofexile.com/?game=poe2&group=1&class=4&item=3408', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(3500);
await p.getByText('Orb of Alchemy', { exact: true }).first().click();
await p.mouse.move(1230, 480); await p.mouse.click(1230, 480);
await p.waitForTimeout(600);
await p.getByText('Desecrate', { exact: true }).first().click();
await p.waitForTimeout(500);
await p.getByText('Preserved Rib', { exact: true }).first().click();
await p.waitForTimeout(1200);
await p.screenshot({ path: 'recon/coe3.png' });
fs.writeFileSync('recon/coe3.html', await p.content());
const txt = await p.evaluate(() => document.body.innerText);
fs.writeFileSync('recon/coe3.txt', txt);
console.log(txt.length);
await b.close();
