import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1500, height: 1000 } });
const errs = []; const bad = [];
p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type() === 'error' && errs.push(m.text()));
p.on('response', r => { if (r.url().includes('/assets/items/') && !r.ok()) bad.push(r.url()); });
await p.goto('http://localhost:5173/?group=1&class=4&item=3408');
await p.waitForSelector('#itemBox');
await p.waitForTimeout(800);
await p.screenshot({ path: 'recon/icons-bar.png', clip: { x: 100, y: 500, width: 1100, height: 330 } });
console.log('currency icons loaded:', await p.$$eval('.cur-icon', is => is.filter(i => i.naturalWidth > 0).length), '/', await p.locator('.cur-icon').count());
await p.click('[data-family] >> nth=0'); await p.click('.cur-wrap.open .cur-drop .cur:has-text("Perfect")');
await p.locator('#itemBox').scrollIntoViewIfNeeded(); await p.evaluate(() => window.scrollBy(0, 250));
const box = await p.locator('#itemBox').boundingBox();
console.log('hidden before hover:', await p.locator('#cursorIcon').isHidden());
await p.mouse.move(box.x + box.width / 2, box.y + 120);
await p.mouse.move(box.x + box.width / 2 + 10, box.y + 130);
console.log('shown over item:', await p.locator('#cursorIcon').isVisible(), '| label:', await p.innerText('#cursorIcon'), '| icon ok:', await p.$eval('#cursorIcon img', i => i.naturalWidth > 0));
await p.screenshot({ path: 'recon/cursor.png' });
await p.mouse.move(100, 100);
console.log('hidden off item:', await p.locator('#cursorIcon').isHidden());
await p.mouse.move(box.x + 100, box.y + 100);
await p.keyboard.press('Escape');
console.log('Esc drops it:', await p.locator('#cursorIcon').isHidden(), await p.evaluate(() => window.__craft.S.method));
console.log('404 icons:', bad);
console.log(errs.join('\n') || 'no errors');
await b.close();
