import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1500, height: 1400 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:5173/?group=1&class=4&item=3408');
await p.waitForSelector('#itemBox');
const tabs = await p.$$eval('[data-tab]', t => t.map(x => x.dataset.tab)); console.log(tabs);
await p.click('[data-tab="Currencies"]');
await p.locator('.cur:not([disabled])').filter({ hasText: /Alchemy/ }).first().click(); await p.click('#itemBox');
await p.locator('.cur').filter({ hasText: /Annul/ }).first().click({ force: true });
await p.waitForSelector('[data-omen]');
await p.waitForTimeout(800);
console.log(await p.$$eval('[data-omen]', bs => bs.map(x => [x.innerText.trim(), x.querySelector('img')?.naturalWidth || 0])));
await p.locator('.chips.sub').first().screenshot({ path: 'recon/omen-icons2.png' });
console.log(errs.join('\n') || 'no errors');
await b.close();
