import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1500, height: 1000 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:5173/?group=1&class=4&item=3408');
await p.waitForSelector('#itemBox');
const state = async () => (await p.$$eval('.cur', bs => bs.filter(x => !x.disabled).map(x => x.innerText.replace(/\n/g, ' ')))).join(' | ');
console.log('normal:', await state());
await p.click('[data-method]:has-text("Perfect Orb of Transmutation")'); await p.click('#itemBox');
console.log(await p.evaluate(() => JSON.stringify(window.__craft.S.item.mods.map(m => window.__craft.DB.mods.get(m.id).minlvl))), '(must be >=70)');
console.log('magic:', await state());
await p.click('[data-method]:has-text("Perfect Orb of Augmentation")'); await p.click('#itemBox');
await p.click('[data-method]:has-text("Perfect Regal Orb")'); await p.click('#itemBox');
await p.click('[data-method]:has-text("Perfect Exalted Orb")'); await p.click('#itemBox');
await p.click('[data-method]:has-text("Perfect Chaos Orb")'); await p.click('#itemBox');
console.log(await p.evaluate(() => JSON.stringify(window.__craft.S.item.mods.map(m => window.__craft.DB.mods.get(m.id).minlvl))), 'rarity', await p.evaluate(() => window.__craft.S.item.rarity));
console.log('rare:', await state());
await p.screenshot({ path: 'recon/mine2.png' });
console.log(errs.join('\n') || 'no errors');
await b.close();
