import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1500, height: 1000 } });
const errs = [];
p.on('pageerror', e => errs.push('PAGEERR ' + e.message));
p.on('console', m => { if (m.type() === 'error') errs.push('CONSOLE ' + m.text()); });
await p.goto('http://localhost:5173/?group=1&class=4&item=3408');
await p.waitForSelector('#itemBox');
await p.click('[data-method]:has-text("Orb of Transmutation") >> nth=0');
await p.click('#itemBox');
await p.click('[data-method]:has-text("Orb of Augmentation") >> nth=0');
await p.click('#itemBox');
await p.click('[data-method]:has-text("Regal Orb") >> nth=0');
await p.click('#itemBox');
await p.click('[data-method]:has-text("Exalted Orb") >> nth=0');
await p.click('#itemBox');
await p.screenshot({ path: 'recon/mine1.png' });
console.log(await p.innerText('#tooltip'));
console.log(errs.join('\n') || 'no errors');
await b.close();
