import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1500, height: 1000 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:5173/');
await p.waitForFunction(() => window.__craft);
const id = await p.evaluate(() => { const D = window.__craft.DB; return [...D.items.values()].find(i => D.text(i.label) === 'Maji Talisman').id; });
await p.goto(`http://localhost:5173/?group=8&class=90&item=${id}`);
await p.waitForSelector('#itemBox');
await p.locator('.cur:has-text("Orb of Alchemy")').click();
await p.locator('#itemBox').scrollIntoViewIfNeeded();
const bx = await p.locator('#itemBox').boundingBox();
await p.mouse.move(bx.x + 80, bx.y + 100); await p.mouse.click(bx.x + 80, bx.y + 100);
const hist = () => p.evaluate(() => window.__craft.S.history.length + ' steps, ' + window.__craft.S.item.rarity);
console.log('after alchemy:', await hist());
await p.locator('#undo').scrollIntoViewIfNeeded();
const ub = await p.locator('#undo').boundingBox();
await p.mouse.move(ub.x + 10, ub.y + 8, { steps: 8 });
console.log('icon hidden while over Undo:', await p.locator('#cursorIcon').isHidden(), '| pointer style:', await p.$eval('#undo', e => getComputedStyle(e).cursor), '| item body style:', await p.$eval('.item-body', e => getComputedStyle(e).cursor));
await p.mouse.down(); await p.mouse.up();
console.log('after Undo click:', await hist());
// Ctrl+Z path too
await p.locator('#itemBox').scrollIntoViewIfNeeded();
const b2 = await p.locator('#itemBox').boundingBox();
await p.mouse.move(b2.x + 80, b2.y + 100); await p.mouse.click(b2.x + 80, b2.y + 100);
console.log('re-applied:', await hist());
await p.keyboard.press('Control+z');
console.log('after Ctrl+Z:', await hist());
console.log(errs.join('\n') || 'no errors');
await b.close();
